### PR TITLE
fix: loader dark background

### LINKED ISSUE #201: Loading dialog does not respect theme selection
When selecting `HCaptchaTheme.DARK` (or a custom theme), the loading dialog still has an explicit white background, which clashes a bit with a dark-mode interface:

Image

I see the loading dialog layout has a hardcoded `android:color/white` as the background -- Could we possibly allow customizing this color via `HCaptchaConfig`?

### PR DESCRIPTION
**Pull request by CAMOBAP**
closes #201

### CODE REVIEW

File: sdk/src/main/java/com/hcaptcha/sdk/HCaptchaDialogFragment.java [hunk 1]
```diff
@@ -169,6 +169,12 @@ public View onCreateView(@Nullable LayoutInflater inflater,
             prepareWebView(rootView, config);
 
             loadingContainer = rootView.findViewById(R.id.loadingContainer);
+            if (loadingContainer != null) {
+                final HCaptchaTheme theme = config.getTheme();
+                final int backgroundColor = (theme == HCaptchaTheme.DARK || theme == HCaptchaTheme.CONTRAST)
+                        ? Color.BLACK : Color.WHITE;
```
Comment (e271828-) [inline sdk/src/main/java/com/hcaptcha/sdk/HCaptchaDialogFragment.java:175]: future TODO: arguably we should extend the custom theming schema to cover the modal.

why CONTRAST? that is a light colored theme.

Comment (e271828-) [reply sdk/src/main/java/com/hcaptcha/sdk/HCaptchaDialogFragment.java]: Probably it should get its own key.
