### PR TITLE
fix: show loading screen until the challenge is open

### LINKED ISSUE #74: Click screen during verify call trigger Challenge Closed Error
If you click screen during the verification call, you may trigger the Challenge Closed Error (before it is even known whether challenge is required) - the call then fails to return any other callbacks.

I would not expect any error to fire in this scenario. 

This is with the builder.size(HCaptchaSize.INVISIBLE)   (no checkbox) mode

And it seems to be possible to recreate whether or not you use builder.loading(true/false)

Samsung S21 Android 12 device
SDK version 3.3.3

### PR DESCRIPTION
**Pull request by wontem**
Close #74

### CODE REVIEW

File: sdk/src/main/java/com/hcaptcha/sdk/HCaptchaDialogFragment.java [hunk 1]
```diff
@@ -166,9 +164,24 @@ public void onAnimationEnd(Animator animation) {
         }
     }
 
+    @Override
+    public void onLoaded() {
+        assert webViewHelper != null;
+
+        // If the size is `invisible` - wait until challenge is shown and handle it in the `onOpen` callback
```
Comment (DSergiu) [inline sdk/src/main/java/com/hcaptcha/sdk/HCaptchaDialogFragment.java:171]: Comment is redundant.

Comment (wontem) [reply sdk/src/main/java/com/hcaptcha/sdk/HCaptchaDialogFragment.java]: Done in https://github.com/hCaptcha/hcaptcha-android-sdk/pull/78/commits/a3f5189bf27feeb1061ddc1b1d6763a91b9a9a93

**Review by DSergiu — APPROVED** [review]
