### PR TITLE
fix(dialog): fixed dim background when checkbox is visible

### LINKED ISSUE #72: Checkbox dialog: background not dimmed
If I use a config with loading = false, the background behind the checkbox dialog is not dimmed.

Samsung S21 Android 12 device
SDK version 3.3.3

### PR DESCRIPTION
**Pull request by CAMOBAP**
Closes #72

### CODE REVIEW

File: sdk/src/main/java/com/hcaptcha/sdk/HCaptchaDialogFragment.java [hunk 1]
```diff
@@ -54,6 +54,8 @@ public final class HCaptchaDialogFragment extends DialogFragment implements IHCa
 
     private LinearLayout loadingContainer;
 
+    private float defaultDimAmount = 0.6f;
```
Comment (DSergiu) [inline sdk/src/main/java/com/hcaptcha/sdk/HCaptchaDialogFragment.java:57]: Let's bump the version and add a changelog.

**Review by DSergiu — APPROVED** [review]
